[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer-runs = 10_000_000

[rpc_endpoints]
amoy = "${RPC_URL}"

[etherscan]
amoy = { key = "${OKLINK_API_KEY}", url = "https://www.oklink.com/api/explorer/v1/contract/verify/async/api/polygonAmoy" }
